
FROM maven:3.9.6-eclipse-temurin-17-alpine AS builder

WORKDIR /app

COPY pom.xml .
RUN mvn dependency:go-offline -B

COPY src ./src

RUN mvn clean package -DskipTests

FROM eclipse-temurin:17-jre-alpine

WORKDIR /app

RUN addgroup -S springgroup && adduser -S springuser -G springgroup

COPY --from=builder /app/target/*.jar app.jar

RUN chown springuser:springgroup app.jar

USER springuser

EXPOSE 8081

ENTRYPOINT ["java", "-jar", "app.jar"]